import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

interface Finding {
  title: string;
  severity: 'high' | 'medium' | 'low';
  description: string;
  negotiationTip?: string;
}

interface LeaseReport {
  fileName?: string;
  state?: string;
  summary: string;
  findings: Finding[];
  keyTerms?: { label: string; value: string }[];
  analyzedAt?: string;
}

function severityColor(s: string) {
  if (s === 'high') return '#dc2626';
  if (s === 'medium') return '#d97706';
  return '#16a34a';
}

function severityLabel(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export async function generateAndSharePdf(report: LeaseReport) {
  const date = report.analyzedAt || new Date().toLocaleDateString();

  const findingsHtml = report.findings
    .map(
      (f) => `
      <div style="border:1px solid #e5e7eb;border-radius:8px;padding:12px;margin-bottom:10px;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;">
          <strong style="font-size:14px;">${escapeHtml(f.title)}</strong>
          <span style="background:${severityColor(f.severity)};color:#fff;font-size:11px;
            padding:3px 10px;border-radius:20px;">${severityLabel(f.severity)}</span>
        </div>
        <p style="font-size:13px;color:#374151;margin:0 0 6px;">${escapeHtml(f.description)}</p>
        ${
          f.negotiationTip
            ? `<p style="font-size:13px;color:#1e40af;background:#eff6ff;border-radius:6px;
                padding:8px;margin:0;"><strong>Negotiation tip:</strong> ${escapeHtml(f.negotiationTip)}</p>`
            : ''
        }
      </div>`
    )
    .join('');

  const termsHtml = (report.keyTerms || [])
    .map(
      (t) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#6b7280;">${escapeHtml(t.label)}</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;font-size:13px;font-weight:600;">${escapeHtml(t.value)}</td>
      </tr>`
    )
    .join('');

  const html = `
  <html><head><meta charset="utf-8" /></head>
  <body style="font-family:Helvetica,Arial,sans-serif;padding:24px;color:#111827;">
    <div style="text-align:center;margin-bottom:24px;">
      <h1 style="font-size:24px;margin:0 0 4px;">LeaseLens Report</h1>
      <p style="font-size:13px;color:#6b7280;margin:0;">
        ${report.fileName ? escapeHtml(report.fileName) + ' • ' : ''}
        ${report.state ? escapeHtml(report.state) + ' • ' : ''}${escapeHtml(date)}
      </p>
    </div>
    <h2 style="font-size:17px;border-bottom:2px solid #f59e0b;padding-bottom:6px;">Summary</h2>
    <p style="font-size:14px;line-height:1.6;">${escapeHtml(report.summary)}</p>
    ${
      termsHtml
        ? `<h2 style="font-size:17px;border-bottom:2px solid #f59e0b;padding-bottom:6px;margin-top:20px;">Key Terms</h2>
           <table style="width:100%;border-collapse:collapse;">${termsHtml}</table>`
        : ''
    }
    <h2 style="font-size:17px;border-bottom:2px solid #f59e0b;padding-bottom:6px;margin-top:20px;">
      Findings (${report.findings.length})
    </h2>
    ${findingsHtml}
    <p style="font-size:11px;color:#9ca3af;margin-top:24px;text-align:center;">
      Generated by LeaseLens. This report is for informational purposes only and is not legal advice.
      AI analysis may miss issues. Consult a tenant-rights organization or attorney for disputes.
    </p>
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share lease report',
    });
  }
  return uri;
}
